### ISSUE TITLE
Arrows should be a list instead of a tuple

### ISSUE THREAD

**Issue by dcampora** [ReedKrawiec/Fen-To-Board-Image#12]
The README.md states that arrows should be specified as `list[(str,str)]`. I interpreted this as a list of tuples, which is incorrect as the text in the readme states (`A list of lists...`) and the code requires (https://github.com/ReedKrawiec/Fen-To-Board-Image/blob/main/fentoboardimage/main.py#L153). I would suggest to change that to `list[list[str, str]]` to be more explicit.

**Comment by ReedKrawiec** [comment]
I'm going to refactor to accept a list of tuples and update the docs to match that.
