### ISSUE TITLE
Flipped variable flips the board on both axes

### ISSUE THREAD

**Issue by menisadi** [ReedKrawiec/Fen-To-Board-Image#3]
I tried rendering a FEN from black's perspective and got the picture flipped also on the horizontal axis (so a d pawn appears
 on the e file, the black king was placed on the d file etc)
![photo_2023-01-22_22-08-56](https://user-images.githubusercontent.com/9539340/213937882-72068137-8de8-4a77-9a2a-bbcba3390009.jpg)

**Comment by ReedKrawiec** [comment]
Should be fixed in the latest version (1.10), if you run into any other problems feel free to open another issue @menisadi

**Comment by menisadi** [comment]
Thanks! Working perfectly!
