### ISSUE TITLE
add coordinates

### ISSUE THREAD

**Issue by nomeutentepippo** [ReedKrawiec/Fen-To-Board-Image#8]
Is is possible to add the algebraic coordinates as optional featues?
Whitin an external border 
![chess-board-setup-the-chess-starting-position](https://github.com/ReedKrawiec/Fen-To-Board-Image/assets/19464758/31cdaa18-79dc-4992-a336-84a9126b7a74)

**Comment by jlkhermes38** [comment]
+1
Hello @ReedKrawiec thanks for this amazing library. I see you already have a PR for this issue, do you know when this feature will be available ?

**Comment by ReedKrawiec** [comment]
> +1 Hello @ReedKrawiec thanks for this amazing library. I see you already have a PR for this issue, do you know when this feature will be available ?

I paused work on this over the holidays, I'll be aiming to finish this over the weekend now that I've got some free time. Thanks for the interest in the library!

**Comment by ReedKrawiec** [comment]
This feature is available in version `1.2.0`! Please let me know if anyone runs into strange behavior / confusion
